name: Build LaTeX Resume

on:
  push:
    branches:
      - main
    paths:
      - 'resume/resume.tex'
      - '.github/workflows/build-resume.yml'

jobs:
  build-resume:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk

      - name: Build Resume PDF
        run: |
          cd resume
          latexmk -pdf resume.tex
          
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        
      - name: Copy PDF to gh-pages branch
        run: |
          mkdir -p gh-pages/resume
          cp resume/resume.pdf gh-pages/resume/
          
      - name: Commit and Push to gh-pages
        run: |
          cd gh-pages
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add resume/resume.pdf
          git commit -m "Update resume PDF" || echo "No changes to commit"
          git push